<div class="p-20 flex-1 bg-[#DCDCDC]">
    <h2 class="text-2xl text-[#4a4845] mb-6 xl:mb-10">Privacy Policy</h2>
    <h3 class="text-xl text-[#5f141e] mb-4">Introduction</h3>
    <p class="text-[#4a4845] mb-8">The following page outlines the Privacy Policy of JustEarn and specifies our stance when it comes to the collection, disclosure and security of information. Please note, that we reserve the right to amend, add or delete from this Privacy Policy at any time without notice being provided. In using our website or proxies, you unequivocally accept our Privacy Policy. If you wish to view the most up to date policy at any time, it can be found at this webpage.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">Data Security</h3>
    <p class="text-[#4a4845] mb-2">Data protection is a top priority at JustEarn. We ensure that all data that is stored is securely encrypted, with only authorised staff members having access to the database in which information is stored in. This extends to the transmission of data over our webpages, which we have secured to ensure that data transfer cannot be easily intercepted by unauthorised or illegal means. We endeavour to make sure that the integrity of our systems is always the most important thing and have spent a significant amount in maintaining our security systems and network.</p>
    <p class="text-[#4a4845] mb-8">As a result, whilst we do not guarantee that unauthorised third parties cannot illegally gain access to sensitive information, we do have various security protocols in place should this occur. You understand that there is a risk that a breach could occur, and this risk is assumed by you. We cannot and do not take any liability for sensitive information that is leaked, stolen or otherwise from unauthorised third parties.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">Collection and Use of Sensitive Information</h3>
    <p class="text-[#4a4845] mb-2">JustEarn requires the collection of certain information to ensure the smooth running and security of our systems and network. As such, we will collect basic user information each time an account is created or an offer is completed. We collect the users username, email address, IP address, offer information and time of action. This will be connected to your account and will enable us to determine if there has been a breach of our Terms of Service when multiple IP addresses are linked to a single account or fraudulant activity is taking place.</p>
    <p class="text-[#4a4845] mb-2">Furthermore, when you sign into JustEarn with a social account, the same information is collected. However, we collect the name, email address and avatar which is connected to the social account used.</p>
    <p class="text-[#4a4845] mb-2">There are times when we collect non-sensitive information about user’s activities on our website – these are only ever used for our own statistics and reviews in order to improve our website.</p>
    <p class="text-[#4a4845] mb-8">Cookies are stored from our website, despite their minimal use, and in using our website you agree to the collection and storage of these cookies.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">Disclosure of Information Policy</h3>
    <p class="text-[#4a4845] mb-2">JustEarn uses a third party offer walls to provide users with offers. We provide those with a user id, but nothing else. They may collect information from the user on their own website or offers exterally from JustEarn.</p>
    <p class="text-[#4a4845] mb-2">We take your data protection and sensitivity very seriously, and as such, we will not sell or disclose your information to third parties for our own benefit. The only official form of communication you will receive from us will be at the creation of your account and other website notification provided you have them enabled. From time to time we may send you promotional emails to keep you up to date with the various offers we have running on our services and products at JustEarn.</p>
    <p class="text-[#4a4845] mb-8">There may be situations where we are required to share your personal details with third parties, such as relevant law enforcement agencies. If we believe that it is reasonably necessary to comply with law enforcement or other regulatory bodies, we may do so without your prior consent or notice. This is to prevent unscrupulous behaviour including, but not limited to, fraud, security breaches or protecting the rights and assets of JustEarn. The disclosure of sensitive information to relevant organisations or authorities is up to the sole discretion of the management of JustEarn, who’s decision on whether or not the information we have collected will be shared or not is final.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">Third Party Services</h3>
    <p class="text-[#4a4845] mb-8">We use third-party services in order to operate our website. Please note that these services may contain links to third-party apps, websites or services that are not operated by us. We make no representation or warranties with regard to and are not responsible for the content, functionality, legality, security, accuracy, or other aspects of such third-party apps, websites or services. Note that, when accessing and/or using these third-party services, their own privacy policy may apply.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">Cookies</h3>
    <p class="text-[#4a4845] mb-4">Some of the advertisers and Web analytics firms used on JustEarn or in connection with our users ads may place “tracking cookies” on your device. These are small text files that can tell such companies what you are doing online, even though they usually don’t record your name or other personally identifiable information. These cookies are used by these companies to try and match ads to a user’s interests. JustEarn may place cookies on your device, in addition to any placed by advertisers. We use information collected from cookies to target the interests of our end users, help us understand how users our using our site, and enhance end users’ experience on the JustEarn. On JustEarn, cookies are used for various reasons:</p>
    <ul class="list-disc list-inside text-[#4a4845] ml-4 mb-4">
    <li>To track your member login</li>
    <li>To track your member ID across other partner services, for example, watching videos to earn points</li>
    </ul>
    <p class="text-[#4a4845] mb-8">You can change the preferences or settings in your Web browser to control cookies. The Help menu on the menu bar of most browsers will tell you how. In some cases, you can choose to accept cookies from the primary site, but block them from third parties. In others, you can block cookies from specific advertisers, or clear out all cookies.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">GDRP</h3>
    <p class="text-[#4a4845] mb-4">If you are located in Europe, please be advised of the following required by the General Data Protection Regulation:</p>
    <ul class="list-disc list-inside text-[#4a4845] ml-4 mb-8">
    <li>JustEarn may provide the Service to Users located in Europe.</li>
    <li>In its interaction with European Users of the Service, JustEarn is a data controller such that we are the organization which decides the purposes for which and the ways in which any personal data that we have collected is used.</li>
    <li>You agree that we are entitled to obtain, use and process the information you provide to us to enable us to discharge the services.</li>
    <li>Our lawful reason for processing your personal information will be "legitimate interests". Under "legitimate interests" we can process your personal information if we have a genuine and legitimate reason and we are not harming any of your rights and interests.</li>
    <li>We will process your persona data in a lawful, fair and transparent manner on only for the legitimate purpose of being able to provide the service.</li>
    <li>We will only request, process and maintain personal information to the extent necessary to be able to provide the Service.</li>
    <li>We will keep in such form that, and only for the duration that, permits identification of data subjects for no longer than necessary.</li>
    <li>We will process personal information in such a manner that ensures appropriate security of the information, including protection against unauthorized processing and accidental loss.</li>
    <li>By submitting your personal demographic information, you are giving explicit consent to JustEarn to receive, process, and transfer to clients who request the surveys, competitions and initiatives through which the information is collected.</li>
    <li>You may withdraw consent at any time and request that your personal information be erased.</li>
    <li>You may request a copy of all personal information maintained about you and request that it be rectified in the event any information is incorrect.</li>
    <li>JustEarn maintains all records in their entirety until and unless the User requests account deletion, at which time we will delete all personal information without undue delay. If you request that we erase your personal information, you will be required to delete your account and will not be eligible to use the service unless you open another account.</li>
    <li>Should you want to request a copy of the information we hold about you, or request that we delete all information, except as required by applicable law, please contact our Data Protection Officer <a class="text-[#5f141e] hover:text-darkercc" href="/support">here</a>.</li>
    </ul>
    <h3 class="text-xl text-[#5f141e] mb-4">Google Analytics</h3>
    <p class="text-[#4a4845] mb-8">This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies”, which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States . In case IP-anonymisation is activated on this website, your IP address will be truncated within the area of Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases the whole IP address will be first transferred to a Google server in the USA and truncated there. The IP-anonymisation is active on this website. Google will use this information on behalf of the operator of this website for the purpose of evaluating your use of the website, compiling reports on website activity for website operators and providing them other services relating to website activity and internet usage. The IP-address, that your Browser conveys within the scope of Google Analytics, will not be associated with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of JustEarn. You can also opt-out from being tracked by Google Analytics with effect for the future by downloading and installing Google Analytics Opt-out Browser Addon for your current web browser: <a class="text-[#5f141e] hover:text-teal-600" href="https://tools.google.com/dlpage/gaoptout" rel="noreferrer" target="_blank">https://tools.google.com/dlpage/gaoptout</a></p>
    <h3 class="text-xl text-[#5f141e] mb-4">Terms of Service</h3>
    <p class="text-[#4a4845] mb-8">To view our terms of service, please refer to our <a class="text-[#5f141e] hover:text-darkercc" href="/terms">Terms of Service</a>.</p>
    <h3 class="text-xl text-[#5f141e] mb-4">Want to know more?</h3>
    <p class="text-[#4a4845] mb-2">If you have any questions in regards to our Privacy Policy, please <a class="text-[#5f141e] hover:text-darkercc" href="/support">contact us</a>.</p>
    <p class="text-[#4a4845] italic opacity-50 text-xs">This Privacy was last updated on March 7, 2023</p>
    </div>