# render.yaml

# Specify the web service for your application.
web:
  - name: JustEarn - Production
    buildCommand: npm install && npm run build
    startCommand: |
      PORT=2053 node dev.js &
      node build/index.js
    env:
      - key: NODE_ENV
        value: production
